<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gmail.zariust</groupId>
    <artifactId>OtherDrops</artifactId>
    <version>3.2.8</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>16</java.version>
    </properties>

    <scm>
        <connection>scm:git:https://github.com/CoolLord22/OtherDrops1.13.git</connection>
        <developerConnection>scm:git:git@github.com:CoolLord22/OtherDrops1.13.git</developerConnection>
        <url>https://github.com/CoolLord22/OtherDrops1.13</url>
        <tag>HEAD</tag>
    </scm>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <sourceDirectory>src/main/java</sourceDirectory>
        <resources>
            <!-- Filter ONLY plugin.yml -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
            <!-- Everything else: no filtering -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>plugin.yml</exclude>
                    <exclude>events/**</exclude>
                    <exclude>plugin.yml.template</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <!-- Java compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <!-- Build number + git revision -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- Works with local git, no pushing required -->
                    <doCheck>false</doCheck>
                    <doUpdate>false</doUpdate>

                    <!-- buildNumber -->
                    <format>{0,number}</format>
                    <items>
                        <item>buildNumber</item>
                    </items>

                    <!-- short git hash -->
                    <shortRevisionLength>7</shortRevisionLength>
                </configuration>
            </plugin>

            <!-- Build 4 mini event jars using AntRun -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <mkdir dir="${project.build.directory}/generated-events"/>
                                <jar destfile="${project.build.directory}/generated-events/Explosions.jar">
                                    <fileset dir="${basedir}/src/main/resources/events/Explosions" includes="event.info"/>
                                </jar>
                                <jar destfile="${project.build.directory}/generated-events/Sheep.jar">
                                    <fileset dir="${basedir}/src/main/resources/events/Sheep" includes="event.info"/>
                                </jar>
                                <jar destfile="${project.build.directory}/generated-events/Trees.jar">
                                    <fileset dir="${basedir}/src/main/resources/events/Trees" includes="event.info"/>
                                </jar>
                                <jar destfile="${project.build.directory}/generated-events/Weather.jar">
                                    <fileset dir="${basedir}/src/main/resources/events/Weather" includes="event.info"/>
                                </jar>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-event-jars</id>
                        <phase>process-classes</phase>
                        <goals><goal>copy-resources</goal></goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/events</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-events</directory>
                                    <includes>
                                        <include>*.jar</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Shade CustomBlockData -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <!-- Relocate CustomBlockData -->
                            <relocations>
                                <relocation>
                                    <pattern>com.jeff_media.customblockdata</pattern>
                                    <shadedPattern>libs.customblockdata</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <!-- Replace this with your package! -->
                                    <shadedPattern>libs.bstats</shadedPattern>
                                </relocation>
                            </relocations>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <finalName>${project.artifactId}-${project.version}-b${buildNumber}</finalName>
    </build>

    <repositories>
        <!-- Spigot Repo -->
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
        </repository>
        <!-- AuthLib Repo -->
        <repository>
            <id>minecraft-repo</id>
            <url>https://libraries.minecraft.net/</url>
        </repository>

        <!-- Heroes -->
        <repository>
            <id>nexus.hc.to</id>
            <url>https://nexus.hc.to/content/repositories/pub_releases/</url>
        </repository>
        <!-- JitPack Repo for plugin deps -->
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <!-- MCMMO Repo -->
        <repository>
            <id>mcmmo-repo</id>
            <url>https://nexus.neetgames.com/repository/maven-public</url>
        </repository>
        <!-- MythicMobs Repo -->
        <repository>
            <id>nexus</id>
            <name>Lumine Releases</name>
            <url>https://mvn.lumine.io/repository/maven-public/</url>
        </repository>
        <!-- PAPI Repo -->
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <!-- WildStacker Repo -->
        <repository>
            <id>bg-repo</id>
            <url>https://repo.bg-software.com/repository/api/</url>
        </repository>
        <!-- WorldEdit Repo -->
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Spigot API -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <!-- CustomBlockData -->
        <dependency>
            <groupId>com.jeff-media</groupId>
            <artifactId>custom-block-data</artifactId>
            <version>2.2.4</version>
            <scope>compile</scope>
        </dependency>
        <!-- BStats -->
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.0.2</version>
            <scope>compile</scope>
        </dependency>
        <!-- AuthLib -->
        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>authlib</artifactId>
            <version>1.5.21</version>
            <scope>provided</scope>
        </dependency>

        <!-- GriefPrevention API -->
        <dependency>
            <groupId>com.github.GriefPrevention</groupId>
            <artifactId>GriefPrevention</artifactId>
            <version>16.18.2</version>
            <scope>provided</scope>
        </dependency>
        <!-- Heroes API -->
        <dependency>
            <groupId>com.herocraftonline.heroes</groupId>
            <artifactId>Heroes</artifactId>
            <version>1.9.30-RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <!-- Jobs API -->
        <dependency>
            <groupId>com.github.Zrips</groupId>
            <artifactId>Jobs</artifactId>
            <version>v4.17.2</version>
            <scope>provided</scope>
        </dependency>
        <!-- MCMMO API -->
        <dependency>
            <groupId>com.gmail.nossr50.mcMMO</groupId>
            <artifactId>mcMMO</artifactId>
            <version>2.2.049</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.sk89q.worldguard</groupId>
                    <artifactId>worldguard-legacy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- MobArena API -->
        <dependency>
            <groupId>com.github.garbagemule</groupId>
            <artifactId>MobArena</artifactId>
            <version>0.109</version>
            <scope>provided</scope>
        </dependency>
        <!-- MythicMobs API -->
        <dependency>
            <groupId>io.lumine</groupId>
            <artifactId>Mythic-Dist</artifactId>
            <version>5.0.2</version>
            <scope>provided</scope>
        </dependency>
        <!-- Placeholder API -->
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.6</version>
            <scope>provided</scope>
        </dependency>
        <!-- Towny API -->
        <dependency>
            <groupId>com.github.TownyAdvanced</groupId>
            <artifactId>Towny</artifactId>
            <version>0.94.0.4</version>
            <scope>provided</scope>
        </dependency>
        <!-- WildStacker API -->
        <dependency>
            <groupId>com.bgsoftware</groupId>
            <artifactId>WildStackerAPI</artifactId>
            <version>2025.2</version>
            <scope>provided</scope>
        </dependency>
        <!-- WorldEdit API -->
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>7.0.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.sk89q.intake</groupId>
                    <artifactId>intake</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bstats</groupId>
                    <artifactId>bstats-bukkit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- WorldGuard API -->
        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-bukkit</artifactId>
            <version>7.0.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.sk89q.intake</groupId>
                    <artifactId>intake</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bstats</groupId>
                    <artifactId>bstats-bukkit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- Vault API -->
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>